/*
 * This source file was generated by the Gradle 'init' task
 */
package scoremecl;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        // Remove or comment out this line if getGreeting does not exist
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
