/*
 * This source file was generated by the Gradle 'init' task
 */
package scoremecl;

import java.util.List;
import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        try {
            LlamaClient client = new LlamaClient();
            List<String> texts = new ArrayList<>();
            texts.add("Hello, how are you today?");
            List<String> responses = client.generateText(texts);

            for (String response : responses) {
                System.out.println("Response: " + response);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

